[book]
authors = ["Alexander Dvorak"]
language = "en"
multilingual = false
src = "src"
title = "Pitch-Yaw-Slide-Mount - Documentation"

[output.html]
default-theme = "light"
title = "Pitch-Yaw-Slide-Mount - Documentation"