# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

CONFIG_GPIO=y

CONFIG_MICROROS=y
CONFIG_MICROROS_TRANSPORT_SERIAL=y
CONFIG_APP_LINK_WITH_MICROROS=y
CONFIG_CPP=y

CONFIG_MAIN_STACK_SIZE=25000
CONFIG_MAIN_THREAD_PRIORITY=3

# CONFIG_PICOLIBC_USE_MODULE=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n

#CONFIG_PTHREAD_IPC=n

CONFIG_POSIX_API=y
#CONFIG_POSIX_CLOCK=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y


CONFIG_LED_STRIP=y
CONFIG_STEPPER=y
CONFIG_COUNTER=y
CONFIG_COUNTER_TMR_ESP32=y
# CONFIG_STEPPER_LOG_LEVEL_DBG=y
CONFIG_STEPPER_LOG_LEVEL_ERR=y
CONFIG_COUNTER_LOG_LEVEL_ERR=y
CONFIG_STEPPER_STEP_DIR_GENERATE_ISR_SAFE_EVENTS=y